name: MiniAnnouncements
version: 1.3
api-version: 1.13
main: me.xiaozhangup.minian.MiniAnnouncement
authors:
  - xiaozhangup
  - Mical
commands:
  miniannouncement:
    aliases:
      - minian
      - ma